//! Render `$DATA_DIR/etc/dnsmasq.conf` (no Omada reservations).

use std::fs;
use std::path::Path;

use crate::config::Config;
use crate::error::{Error, Result};

/// Render a gateway-mode dnsmasq config.
#[must_use]
pub fn render_conf(cfg: &Config, iface: &str, leasefile: &Path, pidfile: &Path) -> String {
    let mask = cfg.gateway.subnet.netmask();
    let start = cfg.range_start_addr();
    let end = cfg.range_end_addr();
    let gw = cfg.gateway.ip;
    let sticky = cfg.dhcp.sticky.trim();
    let mut body = format!(
        "\
# generated by micronet — do not edit
interface={iface}
bind-interfaces
listen-address={gw}
dhcp-range={start},{end},{mask},{sticky}
dhcp-option=option:router,{gw}
dhcp-option=option:dns-server,{gw}
dhcp-leasefile={lease}
pid-file={pid}
dhcp-authoritative
",
        lease = leasefile.display(),
        pid = pidfile.display(),
    );
    if cfg.dns.enabled {
        body.push_str("local=/lan/\n");
        for rec in &cfg.dns.records {
            // Names are validated in Config::validate before apply.
            if let (Ok(name), Ok(target)) = (
                crate::config::normalize_dns_name(&rec.name),
                cfg.dns_record_target(rec),
            ) {
                match target {
                    crate::config::DnsTarget::A(ip) => {
                        body.push_str(&format!("host-record={name},{ip}\n"));
                    }
                    crate::config::DnsTarget::Cname(canon) => {
                        body.push_str(&format!("cname={name},{canon}\n"));
                    }
                }
            }
        }
    }
    body
}

/// Write conf if contents changed. Returns true when the file was rewritten.
pub fn ensure_conf(path: &Path, body: &str) -> Result<bool> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| Error::io_at(parent, e))?;
    }
    let prev = fs::read_to_string(path).unwrap_or_default();
    if prev == body {
        return Ok(false);
    }
    fs::write(path, body).map_err(|e| Error::io_at(path, e))?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;
    use crate::config::Config;
    use std::net::Ipv4Addr;
    use std::path::PathBuf;

    #[test]
    fn render_contains_sticky_7d() {
        let cfg = Config::default();
        let body = render_conf(
            &cfg,
            "eth0",
            Path::new("/data/etc/dnsmasq.leases"),
            Path::new("/data/run/dnsmasq.pid"),
        );
        assert!(body.contains("7d"));
        assert!(body.contains("dhcp-authoritative"));
        assert!(body.contains("option:router,192.168.0.1"));
        assert!(body.contains("dhcp-range=192.168.0.50,192.168.0.200"));
        assert!(body.contains("pid-file=/data/run/dnsmasq.pid"));
        assert!(!body.contains("dhcp-host="));
        // DNS listener must stay on: we hand out option:dns-server = gateway.ip.
        assert!(!body.contains("port=0"));
    }

    #[test]
    fn render_event_subnet() {
        let mut cfg = Config::default();
        cfg.gateway.ip = Ipv4Addr::new(10, 0, 10, 1);
        cfg.gateway.subnet = "10.0.10.0/24".parse().unwrap();
        cfg.dhcp.sticky = "7d".into();
        let body = render_conf(
            &cfg,
            "eth0",
            &PathBuf::from("/tmp/leases"),
            &PathBuf::from("/tmp/dnsmasq.pid"),
        );
        assert!(body.contains("listen-address=10.0.10.1"));
        assert!(body.contains("10.0.10.50,10.0.10.200"));
        assert!(body.contains(",7d"));
        assert!(body.contains("pid-file=/tmp/dnsmasq.pid"));
    }

    #[test]
    fn render_omits_host_record_when_dns_disabled() {
        let mut cfg = Config::default();
        cfg.dns.records = vec![crate::config::DnsRecord {
            name: "bigfred.lan".into(),
            addr: None,
        }];
        let body = render_conf(
            &cfg,
            "eth0",
            Path::new("/data/etc/dnsmasq.leases"),
            Path::new("/data/run/dnsmasq.pid"),
        );
        assert!(!body.contains("host-record="));
        assert!(!body.contains("local=/lan/"));
        assert!(!body.contains("port=0"));
    }

    #[test]
    fn render_host_records_when_enabled() {
        let mut cfg = Config::default();
        cfg.dns.enabled = true;
        cfg.dns.records = vec![
            crate::config::DnsRecord {
                name: "BigFred.lan".into(),
                addr: None,
            },
            crate::config::DnsRecord {
                name: "wizard".into(),
                addr: Some("192.168.0.1".into()),
            },
            crate::config::DnsRecord {
                name: "alias.lan".into(),
                addr: Some("bigfred.lan".into()),
            },
        ];
        let body = render_conf(
            &cfg,
            "eth0",
            Path::new("/data/etc/dnsmasq.leases"),
            Path::new("/data/run/dnsmasq.pid"),
        );
        assert!(body.contains("local=/lan/"));
        assert!(body.contains("host-record=bigfred.lan,192.168.0.1"));
        assert!(body.contains("host-record=wizard,192.168.0.1"));
        assert!(body.contains("cname=alias.lan,bigfred.lan"));
        assert!(!body.contains("port=0"));
    }
}
