//! dnsmasq config generation and reservation merge.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::stack::MacAddr;
use crate::{Error, Result};

pub const DEFAULT_GATEWAY: &str = "10.0.10.1";
pub const DEFAULT_PREFIX: u8 = 24;
pub const DEFAULT_RANGE_START: &str = "10.0.10.50";
pub const DEFAULT_RANGE_END: &str = "10.0.10.200";
pub const DEFAULT_LEASE: &str = "7d";
pub const DEFAULT_CONF_PATH: &str = "/data/etc/dnsmasq.conf";
pub const DEFAULT_RESERVATIONS_PATH: &str = "/data/etc/dnsmasq.reservations.conf";
pub const DEFAULT_LEASEFILE: &str = "/data/etc/dnsmasq.leases";
pub const DEFAULT_ETHERNET_CONF: &str = "/data/etc/configure-ethernet.conf";

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DhcpDefaults {
    pub iface: String,
    pub gateway: String,
    pub range_start: String,
    pub range_end: String,
    pub lease: String,
    pub conf_path: PathBuf,
    pub reservations_path: PathBuf,
    pub leasefile: PathBuf,
}

impl Default for DhcpDefaults {
    fn default() -> Self {
        Self {
            iface: "eth0".to_string(),
            gateway: DEFAULT_GATEWAY.to_string(),
            range_start: DEFAULT_RANGE_START.to_string(),
            range_end: DEFAULT_RANGE_END.to_string(),
            lease: DEFAULT_LEASE.to_string(),
            conf_path: PathBuf::from(DEFAULT_CONF_PATH),
            reservations_path: PathBuf::from(DEFAULT_RESERVATIONS_PATH),
            leasefile: PathBuf::from(DEFAULT_LEASEFILE),
        }
    }
}

/// Render base dnsmasq.conf (idempotent content).
#[must_use]
pub fn render_base_conf(d: &DhcpDefaults) -> String {
    format!(
        "# Generated by configure-dhcp — do not hand-edit the managed block.\n\
interface={iface}\n\
bind-interfaces\n\
listen-address={gw}\n\
dhcp-range={start},{end},255.255.255.0,{lease}\n\
dhcp-option=option:router,{gw}\n\
dhcp-option=option:dns-server,{gw}\n\
dhcp-authoritative\n\
dhcp-leasefile={leasefile}\n\
conf-file={reservations}\n\
",
        iface = d.iface,
        gw = d.gateway,
        start = d.range_start,
        end = d.range_end,
        lease = d.lease,
        leasefile = d.leasefile.display(),
        reservations = d.reservations_path.display(),
    )
}

/// Ensure base conf exists / matches defaults. Returns true if file changed.
pub fn ensure_base_conf(d: &DhcpDefaults) -> Result<bool> {
    let want = render_base_conf(d);
    let changed = match fs::read_to_string(&d.conf_path) {
        Ok(have) => have != want,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => true,
        Err(e) => return Err(Error::io_at(&d.conf_path, e)),
    };
    if changed {
        if let Some(parent) = d.conf_path.parent() {
            fs::create_dir_all(parent).map_err(|e| Error::io_at(parent, e))?;
        }
        fs::write(&d.conf_path, want).map_err(|e| Error::io_at(&d.conf_path, e))?;
    }
    Ok(changed)
}

/// Parse existing dhcp-host lines from a reservations file.
pub fn parse_reservations(text: &str) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some(rest) = line.strip_prefix("dhcp-host=") else {
            continue;
        };
        let mut parts = rest.splitn(2, ',');
        let Some(mac) = parts.next() else { continue };
        let Some(ip) = parts.next() else { continue };
        map.insert(mac.to_ascii_lowercase(), ip.trim().to_string());
    }
    map
}

/// Merge new MAC→IP into reservations; preserves unknown keys. Returns (new text, changed).
pub fn merge_reservations(existing_text: &str, additions: &[(MacAddr, String)]) -> (String, bool) {
    let mut map = parse_reservations(existing_text);
    let mut changed = false;
    for (mac, ip) in additions {
        let key = mac.to_string();
        match map.get(&key) {
            Some(old) if old == ip => {}
            _ => {
                map.insert(key, ip.clone());
                changed = true;
            }
        }
    }
    let mut out = String::from("# Generated/merged by configure-dhcp\n");
    for (mac, ip) in &map {
        out.push_str(&format!("dhcp-host={mac},{ip}\n"));
    }
    let semantic_same = parse_reservations(existing_text) == map && !changed;
    if semantic_same {
        return (out, false);
    }
    let file_changed = existing_text != out;
    (out, file_changed)
}

/// Write reservations file; returns whether content changed.
pub fn write_reservations(path: &Path, additions: &[(MacAddr, String)]) -> Result<bool> {
    let existing = match fs::read_to_string(path) {
        Ok(t) => t,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(Error::io_at(path, e)),
    };
    let (new_text, changed) = merge_reservations(&existing, additions);
    if !changed {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| Error::io_at(parent, e))?;
    }
    fs::write(path, new_text).map_err(|e| Error::io_at(path, e))?;
    Ok(true)
}

/// Ensure configure-ethernet.conf PRIMARY points at event gateway.
pub fn ensure_ethernet_primary(path: &Path, primary: &str) -> Result<bool> {
    let secondary = "192.168.0.120";
    let want = format!(
        "# configure-ethernet static addresses (managed by configure-dhcp when Omada present)\n\
PRIMARY={primary}\n\
SECONDARY={secondary}\n"
    );
    let changed = match fs::read_to_string(path) {
        Ok(have) => !have.lines().any(|l| {
            let l = l.trim();
            l.eq_ignore_ascii_case(&format!("PRIMARY={primary}"))
                || l.eq_ignore_ascii_case(&format!("PRIMARY = {primary}"))
        }),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => true,
        Err(e) => return Err(Error::io_at(path, e)),
    };
    if changed {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).map_err(|e| Error::io_at(parent, e))?;
        }
        fs::write(path, want).map_err(|e| Error::io_at(path, e))?;
    }
    Ok(changed)
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::expect_used,
        clippy::unwrap_used,
        clippy::field_reassign_with_default
    )]

    use super::*;
    use tempfile::tempdir;

    #[test]
    fn render_contains_lease_7d() {
        let d = DhcpDefaults::default();
        let conf = render_base_conf(&d);
        assert!(conf.contains("7d"));
        assert!(conf.contains("10.0.10.50"));
        assert!(conf.contains("10.0.10.1"));
    }

    #[test]
    fn merge_idempotent() {
        let mac = MacAddr::parse("50:c7:bf:01:02:03").expect("mac");
        let (t1, c1) = merge_reservations("", &[(mac.clone(), "10.0.10.11".into())]);
        assert!(c1);
        let (t2, c2) = merge_reservations(&t1, &[(mac, "10.0.10.11".into())]);
        assert!(!c2 || t1 == t2);
        assert!(t2.contains("dhcp-host=50:c7:bf:01:02:03,10.0.10.11"));
    }

    #[test]
    fn ensure_base_conf_writes_once() {
        let dir = tempdir().expect("tmp");
        let mut d = DhcpDefaults::default();
        d.conf_path = dir.path().join("dnsmasq.conf");
        d.reservations_path = dir.path().join("res.conf");
        d.leasefile = dir.path().join("leases");
        assert!(ensure_base_conf(&d).expect("w1"));
        assert!(!ensure_base_conf(&d).expect("w2"));
    }
}
