name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    uses: dcc-bigfred/.github/.github/workflows/rust-release.yml@v2
    with:
      elf_binaries: configure-dhcp-linux-arm64,configure-ethernet-linux-arm64
      elf_section: .micronet.version
      ci_workflow: ci.yml
      ci_scripts_ref: v2
    secrets: inherit
